# Generated by Django 5.2 on 2025-05-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Appetisers', 'Appetisers'), ('Soups & Salads', 'Soups & Salads'), ('Main', 'Main'), ('Side', 'Side'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], default='Main', max_length=50),
        ),
    ]
