# Generated by Django 5.2 on 2025-05-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
