# Generated by Django 5.2 on 2025-05-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_table_number_alter_table_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
